// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSRefectorCurio
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSRefectorCurio.7d2f91a0-c582-4e4b-9355-1f1a8b7134be";
        public const string Name = "CSRefectorCurio";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Nathaniel Moschkin";
        public const string Tags = "";
    }
}
