// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSRefactorCurio
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSRefactorCurio.89917d41-d017-4d22-a06f-a065312f5631";
        public const string Name = "CSRefactorCurio";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Nathaniel Moschkin";
        public const string Tags = "";
    }
}
