//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRefactorCurio.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSRefactorCurio.Globalization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ABORT {
            get {
                return ResourceManager.GetString("ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string BUILD {
            get {
                return ResourceManager.GetString("BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to build the project first..
        /// </summary>
        internal static string BUILD_PROJECT_FIRST {
            get {
                return ResourceManager.GetString("BUILD_PROJECT_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Solution.
        /// </summary>
        internal static string BUILD_SOLUTION {
            get {
                return ResourceManager.GetString("BUILD_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string CLASS {
            get {
                return ResourceManager.GetString("CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string CLASSES {
            get {
                return ResourceManager.GetString("CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string COUNT {
            get {
                return ResourceManager.GetString("COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        internal static string DIRECTORIES {
            get {
                return ResourceManager.GetString("DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string DIRECTORY {
            get {
                return ResourceManager.GetString("DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string DISABLED {
            get {
                return ResourceManager.GetString("DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ENABLED {
            get {
                return ResourceManager.GetString("ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum.
        /// </summary>
        internal static string ENUM {
            get {
                return ResourceManager.GetString("ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        internal static string ENUMS {
            get {
                return ResourceManager.GetString("ENUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand List.
        /// </summary>
        internal static string EXPAND_LIST {
            get {
                return ResourceManager.GetString("EXPAND_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FOLDER {
            get {
                return ResourceManager.GetString("FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string FOLDERS {
            get {
                return ResourceManager.GetString("FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string INTERFACE {
            get {
                return ResourceManager.GetString("INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        internal static string INTERFACES {
            get {
                return ResourceManager.GetString("INTERFACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Build Solution.
        /// </summary>
        internal static string MI_BUILD_SOLUTION {
            get {
                return ResourceManager.GetString("MI_BUILD_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Map Dependencies.
        /// </summary>
        internal static string MI_MAP_DEPENDENCIES {
            get {
                return ResourceManager.GetString("MI_MAP_DEPENDENCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string NAMESPACE {
            get {
                return ResourceManager.GetString("NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        internal static string NAMESPACES {
            get {
                return ResourceManager.GetString("NAMESPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string OBJECT {
            get {
                return ResourceManager.GetString("OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        internal static string OBJECT_TYPE {
            get {
                return ResourceManager.GetString("OBJECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Object In Code.
        /// </summary>
        internal static string OPEN_OBJECT_IN_CODE {
            get {
                return ResourceManager.GetString("OPEN_OBJECT_IN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to proceed?.
        /// </summary>
        internal static string PROCEED_CONFIRM {
            get {
                return ResourceManager.GetString("PROCEED_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string PROJECT {
            get {
                return ResourceManager.GetString("PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string RECORD {
            get {
                return ResourceManager.GetString("RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string RECORDS {
            get {
                return ResourceManager.GetString("RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string REFRESH {
            get {
                return ResourceManager.GetString("REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string RELOAD {
            get {
                return ResourceManager.GetString("RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Result Type.
        /// </summary>
        internal static string REPORT_CHOOSE_RESULT_TYPE {
            get {
                return ResourceManager.GetString("REPORT_CHOOSE_RESULT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Interdependent Namespaces.
        /// </summary>
        internal static string REPORT_MOST_INTERDEPENDENT {
            get {
                return ResourceManager.GetString("REPORT_MOST_INTERDEPENDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Referenced Objects.
        /// </summary>
        internal static string REPORT_MOST_REFERENCED_OBJECTS {
            get {
                return ResourceManager.GetString("REPORT_MOST_REFERENCED_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Spread Out Namespaces.
        /// </summary>
        internal static string REPORT_MOST_SPREAD_OUT {
            get {
                return ResourceManager.GetString("REPORT_MOST_SPREAD_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string REPORTS {
            get {
                return ResourceManager.GetString("REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string RESCAN {
            get {
                return ResourceManager.GetString("RESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Selected Report.
        /// </summary>
        internal static string RUN_SELECTED_REPORT {
            get {
                return ResourceManager.GetString("RUN_SELECTED_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Now.
        /// </summary>
        internal static string SCAN_NOW {
            get {
                return ResourceManager.GetString("SCAN_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string SOLUTION {
            get {
                return ResourceManager.GetString("SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct.
        /// </summary>
        internal static string STRUCT {
            get {
                return ResourceManager.GetString("STRUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs.
        /// </summary>
        internal static string STRUCTS {
            get {
                return ResourceManager.GetString("STRUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    /// &lt;summary&gt;
        ///    /// Time interval length interpretation types
        ///    /// &lt;/summary&gt;
        ///    public enum TimeTypes
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Interpret seconds
        ///        /// &lt;/summary&gt;
        ///        InSeconds,
        ///        /// &lt;summary&gt;
        ///        /// Interpret milliseconds
        ///        /// &lt;/summary&gt;
        ///        InMilliseconds,
        ///
        ///        /// &lt;summary&gt;
        ///        /// Interpret nanoseconds
        ///        /// &lt;/summary&gt;
        ///        InNanoseconds
        ///    }
        ///
        ///    /// &lt;summary&gt;
        ///    /// Methods for converting between Unix a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeSource {
            get {
                return ResourceManager.GetString("TimeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
