//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRefactorCurio.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSRefactorCurio.Globalization.Resources.CodeResources", typeof(CodeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string AccessModifiers_Global {
            get {
                return ResourceManager.GetString("AccessModifiers_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string AccessModifiers_Internal {
            get {
                return ResourceManager.GetString("AccessModifiers_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AccessModifiers_None {
            get {
                return ResourceManager.GetString("AccessModifiers_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string AccessModifiers_Private {
            get {
                return ResourceManager.GetString("AccessModifiers_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        internal static string AccessModifiers_Protected {
            get {
                return ResourceManager.GetString("AccessModifiers_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string AccessModifiers_Public {
            get {
                return ResourceManager.GetString("AccessModifiers_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Modifiers.
        /// </summary>
        internal static string ICodeElement_AccessModifiers {
            get {
                return ResourceManager.GetString("ICodeElement_AccessModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string ICodeElement_Attributes {
            get {
                return ResourceManager.GetString("ICodeElement_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string ICodeElement_DataType {
            get {
                return ResourceManager.GetString("ICodeElement_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generics.
        /// </summary>
        internal static string ICodeElement_Generics {
            get {
                return ResourceManager.GetString("ICodeElement_Generics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Info.
        /// </summary>
        internal static string ICodeElement_ImportInfo {
            get {
                return ResourceManager.GetString("ICodeElement_ImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritances.
        /// </summary>
        internal static string ICodeElement_Inheritances {
            get {
                return ResourceManager.GetString("ICodeElement_Inheritances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance String.
        /// </summary>
        internal static string ICodeElement_InheritanceString {
            get {
                return ResourceManager.GetString("ICodeElement_InheritanceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Abstract.
        /// </summary>
        internal static string ICodeElement_IsAbstract {
            get {
                return ResourceManager.GetString("ICodeElement_IsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Async.
        /// </summary>
        internal static string ICodeElement_IsAsync {
            get {
                return ResourceManager.GetString("ICodeElement_IsAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Explicit.
        /// </summary>
        internal static string ICodeElement_IsExplicit {
            get {
                return ResourceManager.GetString("ICodeElement_IsExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Extern.
        /// </summary>
        internal static string ICodeElement_IsExtern {
            get {
                return ResourceManager.GetString("ICodeElement_IsExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Implicit.
        /// </summary>
        internal static string ICodeElement_IsImplicit {
            get {
                return ResourceManager.GetString("ICodeElement_IsImplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is New.
        /// </summary>
        internal static string ICodeElement_IsNew {
            get {
                return ResourceManager.GetString("ICodeElement_IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Override.
        /// </summary>
        internal static string ICodeElement_IsOverride {
            get {
                return ResourceManager.GetString("ICodeElement_IsOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Read Only.
        /// </summary>
        internal static string ICodeElement_IsReadOnly {
            get {
                return ResourceManager.GetString("ICodeElement_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Sealed.
        /// </summary>
        internal static string ICodeElement_IsSealed {
            get {
                return ResourceManager.GetString("ICodeElement_IsSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Static.
        /// </summary>
        internal static string ICodeElement_IsStatic {
            get {
                return ResourceManager.GetString("ICodeElement_IsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Virtual.
        /// </summary>
        internal static string ICodeElement_IsVirtual {
            get {
                return ResourceManager.GetString("ICodeElement_IsVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string ICodeElement_Kind {
            get {
                return ResourceManager.GetString("ICodeElement_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Params.
        /// </summary>
        internal static string ICodeElement_MethodParams {
            get {
                return ResourceManager.GetString("ICodeElement_MethodParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Params String.
        /// </summary>
        internal static string ICodeElement_MethodParamsString {
            get {
                return ResourceManager.GetString("ICodeElement_MethodParamsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ICodeElement_Name {
            get {
                return ResourceManager.GetString("ICodeElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Clause.
        /// </summary>
        internal static string ICodeElement_WhereClause {
            get {
                return ResourceManager.GetString("ICodeElement_WhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MarkerKind_Add {
            get {
                return ResourceManager.GetString("MarkerKind_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string MarkerKind_Attribute {
            get {
                return ResourceManager.GetString("MarkerKind_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Comment.
        /// </summary>
        internal static string MarkerKind_BlockComment {
            get {
                return ResourceManager.GetString("MarkerKind_BlockComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string MarkerKind_Case {
            get {
                return ResourceManager.GetString("MarkerKind_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string MarkerKind_Class {
            get {
                return ResourceManager.GetString("MarkerKind_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string MarkerKind_Code {
            get {
                return ResourceManager.GetString("MarkerKind_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidation.
        /// </summary>
        internal static string MarkerKind_Consolidation {
            get {
                return ResourceManager.GetString("MarkerKind_Consolidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const.
        /// </summary>
        internal static string MarkerKind_Const {
            get {
                return ResourceManager.GetString("MarkerKind_Const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor.
        /// </summary>
        internal static string MarkerKind_Constructor {
            get {
                return ResourceManager.GetString("MarkerKind_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom1.
        /// </summary>
        internal static string MarkerKind_Custom1 {
            get {
                return ResourceManager.GetString("MarkerKind_Custom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom2.
        /// </summary>
        internal static string MarkerKind_Custom2 {
            get {
                return ResourceManager.GetString("MarkerKind_Custom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom3.
        /// </summary>
        internal static string MarkerKind_Custom3 {
            get {
                return ResourceManager.GetString("MarkerKind_Custom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom4.
        /// </summary>
        internal static string MarkerKind_Custom4 {
            get {
                return ResourceManager.GetString("MarkerKind_Custom4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        internal static string MarkerKind_Delegate {
            get {
                return ResourceManager.GetString("MarkerKind_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructor.
        /// </summary>
        internal static string MarkerKind_Destructor {
            get {
                return ResourceManager.GetString("MarkerKind_Destructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive.
        /// </summary>
        internal static string MarkerKind_Directive {
            get {
                return ResourceManager.GetString("MarkerKind_Directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string MarkerKind_Do {
            get {
                return ResourceManager.GetString("MarkerKind_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do While.
        /// </summary>
        internal static string MarkerKind_DoWhile {
            get {
                return ResourceManager.GetString("MarkerKind_DoWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else.
        /// </summary>
        internal static string MarkerKind_Else {
            get {
                return ResourceManager.GetString("MarkerKind_Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else If.
        /// </summary>
        internal static string MarkerKind_ElseIf {
            get {
                return ResourceManager.GetString("MarkerKind_ElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum.
        /// </summary>
        internal static string MarkerKind_Enum {
            get {
                return ResourceManager.GetString("MarkerKind_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum Value.
        /// </summary>
        internal static string MarkerKind_EnumValue {
            get {
                return ResourceManager.GetString("MarkerKind_EnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string MarkerKind_Event {
            get {
                return ResourceManager.GetString("MarkerKind_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit Implementation.
        /// </summary>
        internal static string MarkerKind_ExplicitImplementation {
            get {
                return ResourceManager.GetString("MarkerKind_ExplicitImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Reference.
        /// </summary>
        internal static string MarkerKind_ExternalReference {
            get {
                return ResourceManager.GetString("MarkerKind_ExternalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string MarkerKind_Field {
            get {
                return ResourceManager.GetString("MarkerKind_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Value.
        /// </summary>
        internal static string MarkerKind_FieldValue {
            get {
                return ResourceManager.GetString("MarkerKind_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string MarkerKind_Fixed {
            get {
                return ResourceManager.GetString("MarkerKind_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Each.
        /// </summary>
        internal static string MarkerKind_ForEach {
            get {
                return ResourceManager.GetString("MarkerKind_ForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Loop.
        /// </summary>
        internal static string MarkerKind_ForLoop {
            get {
                return ResourceManager.GetString("MarkerKind_ForLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string MarkerKind_Get {
            get {
                return ResourceManager.GetString("MarkerKind_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string MarkerKind_If {
            get {
                return ResourceManager.GetString("MarkerKind_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string MarkerKind_Interface {
            get {
                return ResourceManager.GetString("MarkerKind_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Block Level.
        /// </summary>
        internal static string MarkerKind_IsBlockLevel {
            get {
                return ResourceManager.GetString("MarkerKind_IsBlockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Code Level.
        /// </summary>
        internal static string MarkerKind_IsCodeLevel {
            get {
                return ResourceManager.GetString("MarkerKind_IsCodeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Comment.
        /// </summary>
        internal static string MarkerKind_LineComment {
            get {
                return ResourceManager.GetString("MarkerKind_LineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string MarkerKind_Lock {
            get {
                return ResourceManager.GetString("MarkerKind_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string MarkerKind_Method {
            get {
                return ResourceManager.GetString("MarkerKind_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string MarkerKind_Namespace {
            get {
                return ResourceManager.GetString("MarkerKind_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string MarkerKind_Operator {
            get {
                return ResourceManager.GetString("MarkerKind_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string MarkerKind_Property {
            get {
                return ResourceManager.GetString("MarkerKind_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string MarkerKind_Record {
            get {
                return ResourceManager.GetString("MarkerKind_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MarkerKind_Remove {
            get {
                return ResourceManager.GetString("MarkerKind_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string MarkerKind_Set {
            get {
                return ResourceManager.GetString("MarkerKind_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct.
        /// </summary>
        internal static string MarkerKind_Struct {
            get {
                return ResourceManager.GetString("MarkerKind_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string MarkerKind_Switch {
            get {
                return ResourceManager.GetString("MarkerKind_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        internal static string MarkerKind_This {
            get {
                return ResourceManager.GetString("MarkerKind_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsafe.
        /// </summary>
        internal static string MarkerKind_Unsafe {
            get {
                return ResourceManager.GetString("MarkerKind_Unsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using.
        /// </summary>
        internal static string MarkerKind_Using {
            get {
                return ResourceManager.GetString("MarkerKind_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Block.
        /// </summary>
        internal static string MarkerKind_UsingBlock {
            get {
                return ResourceManager.GetString("MarkerKind_UsingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While.
        /// </summary>
        internal static string MarkerKind_While {
            get {
                return ResourceManager.GetString("MarkerKind_While", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Doc.
        /// </summary>
        internal static string MarkerKind_XMLDoc {
            get {
                return ResourceManager.GetString("MarkerKind_XMLDoc", resourceCulture);
            }
        }
    }
}
