// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSRefactorCurio.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCSRefactorCurioPackageString = "c9b89645-59a8-4d6b-ac62-25631a5bfe54";
        public static Guid guidCSRefactorCurioPackage = new Guid(guidCSRefactorCurioPackageString);

        public const string guidCSRefactorCurioPackageCmdSetString = "d9f078b2-f2e7-4716-9cc3-5b165ff8fba8";
        public static Guid guidCSRefactorCurioPackageCmdSet = new Guid(guidCSRefactorCurioPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowClassFromJsonCommand = 0x1021;
        public const int ShowCurioExplorerCommand = 0x1022;
        public const int RefactorCurioGroup = 0x1012;
        public const int RefactorCurioProjectGroup = 0x1013;
    }
}